name: czech-gpt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - pip:
    - bitsandbytes==0.41.3.post2
    - boto3==1.35.26
    - comet_ml==3.50.0
    - huggingface-hub==0.34.4
    - jupyter==1.1.1
    - langdetect==1.0.9
    - loguru==0.7.3
    - matplotlib==3.10.3
    - multiprocess==0.70.16
    - pandas==2.2.3
    - peft==0.8.2
    - pyrallis==0.3.1
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - seaborn==0.13.2
    - tensor-parallel==1.0.17
